version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html